import os, json
from pprint import pprint
import pyperclip

## Parameters
ToMap = {
    # "shouldHaveParent": "",
    # "parents": "[[Scripts#Parent blocks|Parent blocks]]",
    # "needsChildren": "[[Scripts#Children blocks|Children blocks]]",
    # "ID": "[[Scripts#ID|ID]]",
    "softOverride": "[[Scripts#Soft overrides|Soft overrides]]",
}

SCRIPT_PATH = os.path.dirname(__file__)
path = os.path.join(SCRIPT_PATH, "..", "pz-scripts-data", "data", "scriptBlocks.json")
path = os.path.abspath(path)

with open(path, 'r') as file:
    data = json.load(file)

block_name = input("Block\n> ")
# block_name = "item" # DEBUG
# block_name = "craftRecipe" # DEBUG
block_data = data.get(block_name)
if block_data is None:
    print(f"Block not found: {block_name}")
    exit(1)

print(f"Block found: {block_name}")


## Utility

def find_potential_children(block_name):
    children = []
    for potential_child_name, potential_child_data in data.items():
        parents = potential_child_data.get("parents", [])
        if block_name in parents:
            children.append(potential_child_name)
    return children

def make_infobox(name):
    infobox = """{{Infobox
| title = ${name}
| class = theme-blue
| <!-- AUTOGENERATED -->
${sections}
}}
"""
    infobox = infobox.replace("${name}", name)
    return infobox    

id = 1
def make_section(name):
    global id
    section = """    {{Infobox/section
    | id = ${id}
    | 1 = ${name}
    | 2 =
${rows}
    }}"""
    section = section.replace("${name}", name)
    section = section.replace("${id}", str(id))
    id += 1
    return section

def make_row(name, text, parameterData):
    row = """        {{Infobox/row
        | 1 = ${text}
        | 2 = ${parameterData}
        }}"""
    # row = row.replace("${name}", name)
    row = row.replace("${text}", text)
    row = row.replace("${parameterData}", str(parameterData))
    return row

def format_list(list, formatting="[[{item} (scripts)|{item}]]", required=[]):
    txt = [formatting.format(item=item) for item in list]
    result = "<br>".join(txt)
    return result.strip()



## Formatting

# basic structure
infobox = make_infobox(block_name)
section = make_section("Properties")
rows = []




# list parents
potential_parents = block_data.get("parents", [])
parents = format_list(potential_parents)

row = make_row("Parents", "[[Scripts#Parent blocks|Parent blocks]]", parents)
rows.append(row)


# list children
potential_children = find_potential_children(block_name)
required = block_data.get("needsChildren", []) if not block_data.get("softOverride") else []
children = format_list(potential_children, required=required)

row = make_row("Children", "[[Scripts#Children blocks|Children blocks]]", children)
rows.append(row)


# list IDs or "Any"
ids = block_data.get("ID", None)
values = False
if ids is not None:
    values = ids.get("values", "Any")
    if values == "Any":
        parentsWithout = ids.get("parentsWithout", None)
        if parentsWithout is not None and len(parentsWithout) > 0:
            values = f"Any except when parent is:<br>{format_list(parentsWithout)}"

if type(values) is list:
    values = format_list(values)

row = make_row("ID", "[[Scripts#ID|ID]]", values)
rows.append(row)


# soft override
softOverride = block_data.get("softOverride", "Need testing")
row = make_row("Soft override", "[[Scripts#Soft overrides|Soft overrides]]", str(softOverride))
rows.append(row)



# # format generic properties
# for toMap, text in ToMap.items():
#     parameterData = block_data.get(toMap)
#     if parameterData is None:
#         continue
#     row = make_row(toMap, text, parameterData)
#     rows.append(row)





section = section.replace("${rows}", "\n".join(rows))
infobox = infobox.replace("${sections}", section).strip()


print(infobox)
pyperclip.copy(infobox)